name: Healthcare NGO System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Backend Dependencies
      run: |
        cd server
        npm ci
        
    - name: Build Backend
      run: |
        cd server
        npm run build
        
    - name: Install Frontend Dependencies
      run: |
        cd client
        npm ci
        
    - name: Build Frontend
      run: |
        cd client
        npm run build
        
    - name: Run Backend Tests
      run: |
        cd server
        npm test
      
    - name: Run Frontend Tests
      run: |
        cd client
        npm test -- --passWithNoTests
